2024-09-04 13:38:58,161 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 13:38:58,162 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 13:38:58,163 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2024-09-04 13:40:01,574 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 13:40:01,575 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 13:40:01,645 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-11' coro=<UpdateMethods._dispatch_update() done, defined at /home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/updates.py:521> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/home/mohammad/Documents/Project/PlusSaver/bot/modules/handlers/handlers.py", line 432, in get_url
    media = youtube_client.download_video()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/bot/modules/downloaders/youtube.py", line 54, in download_video
    info_dict = ydl.extract_info(self.url, download=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4255, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4219, in _download_player_responses
    player_responses, player_url = self._extract_player_responses(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 3840, in _extract_player_responses
    pr = pr or self._extract_player_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 3737, in _extract_player_response
    return self._extract_response(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 1012, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 656, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 328, in _send
    requests_res = session.request(
                   ^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
2024-09-04 14:02:51,822 - telethon.network.connection.connection - WARNING - Server closed the connection: 0 bytes read on a total of 8 expected bytes
2024-09-04 14:02:51,823 - telethon.network.mtprotosender - INFO - Connection closed while receiving data: 0 bytes read on a total of 8 expected bytes
2024-09-04 14:02:51,823 - telethon.network.mtprotosender - INFO - Closing current connection to begin reconnect...
2024-09-04 14:02:51,823 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.91:443/TcpFull...
2024-09-04 14:02:51,825 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.91:443/TcpFull complete!
2024-09-04 14:02:52,125 - telethon.network.connection.connection - WARNING - Server closed the connection: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,126 - telethon.network.mtprotosender - INFO - Connection closed while receiving data: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,126 - telethon.network.mtprotosender - INFO - Closing current connection to begin reconnect...
2024-09-04 14:02:52,126 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.91:443/TcpFull...
2024-09-04 14:02:52,127 - telethon.network.connection.connection - INFO - <class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,127 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.91:443/TcpFull complete!
2024-09-04 14:02:52,427 - telethon.network.connection.connection - WARNING - Server closed the connection: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,428 - telethon.network.mtprotosender - INFO - Connection closed while receiving data: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,428 - telethon.network.mtprotosender - INFO - Closing current connection to begin reconnect...
2024-09-04 14:02:52,428 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.91:443/TcpFull...
2024-09-04 14:02:52,429 - telethon.network.connection.connection - INFO - <class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,429 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.91:443/TcpFull complete!
2024-09-04 14:02:52,730 - telethon.network.connection.connection - WARNING - Server closed the connection: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,731 - telethon.network.mtprotosender - INFO - Connection closed while receiving data: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,731 - telethon.network.mtprotosender - INFO - Closing current connection to begin reconnect...
2024-09-04 14:02:52,731 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.91:443/TcpFull...
2024-09-04 14:02:52,732 - telethon.network.connection.connection - INFO - <class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
2024-09-04 14:02:52,732 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.91:443/TcpFull complete!
2024-09-04 14:02:53,033 - telethon.network.connection.connection - WARNING - Server closed the connection: [Errno 104] Connection reset by peer
2024-09-04 14:02:53,033 - telethon.network.mtprotosender - INFO - Connection closed while receiving data: [Errno 104] Connection reset by peer
2024-09-04 14:02:53,033 - telethon.network.mtprotosender - INFO - Closing current connection to begin reconnect...
2024-09-04 14:02:53,033 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.91:443/TcpFull...
2024-09-04 14:02:53,034 - telethon.network.connection.connection - INFO - <class 'ConnectionResetError'> during disconnect: [Errno 104] Connection reset by peer
2024-09-04 14:02:53,034 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.91:443/TcpFull complete!
2024-09-04 14:03:07,554 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 14:03:07,555 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 14:03:07,556 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2024-09-04 14:04:08,690 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 14:04:08,691 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 14:04:08,692 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2024-09-04 14:05:11,925 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 14:05:11,926 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 14:05:11,926 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2024-09-04 14:06:18,568 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 14:06:18,569 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 14:06:18,570 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2024-09-04 14:06:33,462 - telethon.client.updates - ERROR - Unhandled exception on get_url
Traceback (most recent call last):
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/home/mohammad/Documents/Project/PlusSaver/bot/modules/handlers/handlers.py", line 433, in get_url
    await send_media(event, media)
  File "/home/mohammad/Documents/Project/PlusSaver/bot/modules/handlers/handlers.py", line 34, in send_media
    await client.send_file(event.chat_id, file=media.MEDIA, caption=Strings.media_geted(media.TITLE, media.CAPTION), reply_to=event.id)
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/uploads.py", line 430, in send_file
    return self._get_response_message(request, await self(request), entity)
                                               ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/Documents/Project/PlusSaver/venv/lib/python3.11/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.MediaCaptionTooLongError: The caption is too long (caused by SendMediaRequest)
2024-09-04 14:07:10,468 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 14:07:10,469 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 14:07:10,470 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
2024-09-04 14:09:46,445 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.91:443/TcpFull...
2024-09-04 14:09:46,445 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.91:443/TcpFull complete!
2024-09-04 14:09:46,446 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
